sonar.projectKey=laboratorepo
sonar.projectName=LaboratoRepo

sonar.sources=djangotutorial
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/db.sqlite3,**/node_modules/**

sonar.tests=djangotutorial
sonar.test.inclusions=**/tests.py

sonar.python.version=3.12
sonar.python.coverage.reportPaths=djangotutorial/coverage.xml
